language: python
python:
  - "3.3"

install:
  - pip install -e .
  - pip install coveralls

before_script:
  - mkdir cached_html

script:
  - coverage run -m unittest discover

after_success: coveralls
